# Generated by Django 4.2.5 on 2023-10-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(default='non password', max_length=100),
        ),
    ]
